const ui = {
    textareaInput: document.getElementById('textarea-input'),
    occurrenceSpan: document.getElementById('occurrence-value'),
    wordLengthInput: document.getElementById('length'),
    wordLengthSpan: document.getElementById('length-value'),
    abbreviationLengthInput: document.getElementById('abbreviation-length'),
    abbreviationLengthSpan: document.getElementById('abbreviation-length-value'),
    outputCont: document.getElementById('text-output-container'),
    wordCountOutput: document.getElementById('word-count'),
    charCountOutput: document.getElementById('char-count'),
    relativeChangeOutput: document.getElementById('relative-change'),
    regexInput: document.getElementById('regex-input'),
    advancedSettingsError: document.getElementById('advanced-settings-error'),
    submitNewRegexButton: document.getElementById('submit-new-regex-button'),
    resetRegexButton: document.getElementById('reset-regex-button'),
    closeAndRunButton: document.getElementById('close-and-run-button'),
    aboutContainer: document.getElementById('about-container'),
    advancedSettingsContainer: document.getElementById('advanced-settings-container'),
    modalBackground: document.getElementById('modal-background'),
    occurrenceInput: document.getElementById('occurrence'),
    wordLength: document.getElementById('wordLength'),
    aboutContainerCloseButton: document.getElementById('about-container-close-button'),
    aboutButton: document.getElementById('about-button'),
    advancedSettingsButton: document.getElementById('advanced-settings-button'),
}
export default ui;